### ISSUE TITLE
Unexpected results on processed image

### ISSUE THREAD

**Issue by javierlorenzod** [vita-epfl/monoloco#20]
Hello!

First of all, thanks for sharing your job I found it helpful and really interesting. I have a problem with one of the images that I have processed. In the image there are one woman and a child and they are really close in the scene. However when I process the image I have the following results:
![01506 png combined](https://user-images.githubusercontent.com/6094231/76782215-389deb80-67b0-11ea-88a7-1f079bc7672b.png)
I thought that it was because I did not use an intrinsic matrix. I followed the issue #18 and I changed the matrix returned in function `factory_for_gt` in `process.py`, obtaining similar results, shown in the following image:
![01506 png combined2](https://user-images.githubusercontent.com/6094231/76782119-1310e200-67b0-11ea-93d0-f3d087c43aef.png)
You said in the README that the relative distances are still meaningful , but seeing the results seems that the relative distances are also strange. Is there anything that I am doing wrong?

Thank you

JLD

**Comment by bertoni9** [comment]
Hello JLD, 
Thank you for your interest in the project! There is an intrinsic ambiguity in detecting humans from RGB images and your are showing the most critical case: small children which are predicted as far adults. I suspect that fish-eye images may also amplify this effect due to the  greater distortion in the corners but the ambiguity remains in normal images as well.
Hope it helps,
Lorenzo
