### ISSUE TITLE
Reading an Image from ros-topic

### ISSUE THREAD

**Issue by AbdelrahmanAEmam** [vita-epfl/monoloco#24]
I am using Monoloco in a Mobile robot application using ROS that I am currently developing, if you don't mind I need some help regarding Monoloco.
I am quite familiar with using Monoloco with pictures using --glob argument as mentioned in the repo, now I am trying to apply Monoloco on an image coming from ros-topic,
1) Is Monoloco available to be used in this scenario or it must have the image existing on the system ?
2) From the help I noticed that _glob argument_ is used to add image(s) to Monoloco, What's the _image argument_ then and how can I use the image argument?

That's not an issue with the network it's quite perfect, Just a problem I've been struggling with regarding Monoloco, so if you could give me any hint this would be great. 
Thanks in Advance.

**Comment by bertoni9** [comment]
Hello, 
I am not familiar with ROS unfortunately, but regarding your questions:
1. I am not sure what you mean by "existing in the system". For example, you can use MonoLoco directly from the webcam. Similarly, I think it should be possible to adapt it to your scenarios.
2. There is a bit of redundancy. The command _image_ comes from openpifpaf and the allows to pass the image path instead of a glob  expressions. You can use either one or the other.

Best,
Lorenzo
