### ISSUE TITLE
Question about [geometric_baseline]

### ISSUE THREAD

**Issue by chenhao-1115** [vita-epfl/monoloco#38]
HI. Thank you for your open-source program. 
I have one question about geometric_baseline program:
In the geometric method, how did the following matrix(**matrix,bb**) be obtained?

def **compute_distance**(xyz_norm_1, xyz_norm_2, average_y, mode='average', dy_met=0):
    """
    Compute distance Z of a mask annotation (solving a linear system) for 2 possible cases:
    1. knowing specific height of the annotation (head-ankle) dy_met
    2. using mean height of people (average_y)
    """
    assert mode in ('average', 'real')

    x1 = float(xyz_norm_1[0])
    y1 = float(xyz_norm_1[1])
    x2 = float(xyz_norm_2[0])
    y2 = float(xyz_norm_2[1])
    xx = (x1 + x2) / 2

    # Choose if solving for provided height or average one.
    if mode == 'average':
        cc = - average_y  # Y axis goes down
    else:
        cc = -dy_met

    # Solving the linear system Ax = b
    **matrix** = np.array([[y1, 0, -xx],
                       [0, -y1, 1],
                       [y2, 0, -xx],
                       [0, -y2, 1]])

    **bb** = np.array([cc * xx, -cc, 0, 0]).reshape(4, 1)
    xx = np.linalg.lstsq(matrix, bb, rcond=None)
    z_met = abs(np.float(xx[0][1]))  # Abs take into account specularity behind the observer

    return z_met

**Comment by bertoni9** [comment]
Hello,

Thank you for your interest in our work. The matrix A and the vector b are obtained from a linear system of equations. Here a brief explanations of it.

Our goal is to find the 3D location of the person assuming he is 1.7m tall. Considering head and feet for example, we can find the equation of the lines in the space that goes from the origin (camera) and reach the person. We know the 3D coordinates of the origin (0,0,0) and the normalised image coordinates of the two points (x1, y1 z1=1) and (x2, y2, z2=1). The latter can be obtained from the pixel coordinates using the camera intrinsic matrix. 

Once we have the equations of these lines, we want to find the 3D locations where the two lines have 1.7 meters distance, namely (x*, y,* z*) and (x*, y*+1.7, z*). This will result in an over-constrained system of 4 equations and 3 unknown (x*,y*,z*). This is expected because not all pairs of lines satisfy this requirement.

To construct the linear system you can start from the equation of a line in the space between two points: 

(x-x0)/(x1-x0) = (y-y0)/(y1-y0) = (z-z0)/(z1-z0)

and for the second line
(x-x0)/(x2-x0) = (y-y0)/(y2-y0) = (z-z0)/(z2-z0)

Where 0 is the origin and 1, 2 are normalized  image coordinate locations (z1=z2=1)

After, you substitute the variables x,y,z with the unknown location x*, y*,z* (first line) or with x*,y*+1.7, z* in line 2 and you solve the system.

Hope it helps!
Lorenzo
